// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // These values are from your actual Firebase project
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD97rcYDuLVYcyTM2jHggFMdg3xMlKLpws',
    appId: '1:827150327810:android:251c2339ea49e54506c71b',
    messagingSenderId: '827150327810',
    projectId: 'roommatch-458521',
    storageBucket: 'roommatch-458521.firebasestorage.app',
  );

  // iOS values - Will need to be updated if you add iOS support to your Firebase project
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD97rcYDuLVYcyTM2jHggFMdg3xMlKLpws', // Using Android API key as placeholder
    appId: '1:827150327810:ios:iosappidhere',  // You'll need a real iOS app ID from Firebase console
    messagingSenderId: '827150327810',  // Same as Android
    projectId: 'roommatch-458521',  // Same as Android
    storageBucket: 'roommatch-458521.firebasestorage.app',  // Same as Android
    iosClientId: 'ios-client-id-needed-here.apps.googleusercontent.com', // From Firebase iOS app registration
    iosBundleId: 'com.rentmate.rent_mate',  // Your iOS bundle ID
  );
}
